site_name: 技术笔记
theme:
  name: material
  language: zh
  favicon: ../../favicon.jpg
  custom_dir: overrides
  palette:
    primary: blue
    accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
extra:
  homepage: ../../tech/index.html
nav:
  - Home: index.md
  - ISEE: ISEE/index.md
  - CS: CS/index.md
  - AI: AI/index.md
  - Me: Me/index.md
  - Math: Math/index.md
  - Physics: Physics/index.md
  - Other: Other/index.md
  - 通识: 通识/index.md
