site_name: 文艺笔记
site_url: https://ladygege2494.github.io/notes/art/
site_description: GegeNook 的电影、文学、艺术与文化笔记
site_author: LadyGege
theme:
  name: material
  language: zh
  favicon: /favicon.jpg
  icon:
    logo: material/palette-outline
  custom_dir: ../overrides
  font: false
  palette:
    - scheme: default
      primary: deep purple
      accent: pink
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    - scheme: slate
      primary: deep purple
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
extra:
  homepage: /art/
extra_css:
  - /assets/mkdocs-extra.css
extra_javascript:
  - /assets/mkdocs.js
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - search:
      lang: zh
      separator: '[\s\-，。；：！？、（）【】《》]+'
      fields:
        title:
          boost: 1000
        text:
          boost: 1
        tags:
          boost: 30
nav:
  - Home: index.md
  - Film:
    - "概览": Film/index.md
    - "《花样年华》": Film/《花样年华》.md
    - "《认识电影》书摘": Film/《认识电影》书摘.md
  - Fine Art:
    - "概览": Fine Art/index.md
    - "艺术史": Fine Art/艺术史.md
    - "设计风格汇总": Fine Art/设计风格汇总.md
  - Literature:
    - "概览": Literature/index.md
    - "伍尔夫——关于意识流与女性的困境": Literature/伍尔夫——关于意识流与女性的困境.md
  - Music:
    - "概览": Music/index.md
    - "古典音乐": Music/古典音乐.md
    - "流行演唱": Music/流行演唱.md
  - History:
    - "概览": History/index.md
  - Philosophy:
    - "概览": Philosophy/index.md
    - "辩论": Philosophy/辩论.md
  - Culture:
    - "概览": Culture/index.md
    - "国家图鉴": Culture/国家图鉴.md
    - "日本三大主流审美意识形态": Culture/日本三大主流审美意识形态.md
    - "梦核，当代年轻人的新型电子止疼药": Culture/梦核，当代年轻人的新型电子止疼药.md
    - "香水": Culture/香水.md
  - Inspiration:
    - "概览": Inspiration/index.md
    - "Filmilism": Inspiration/Filmilism.md
  - Language:
    - "概览": Language/index.md
    - "English": Language/English.md
    - "French": Language/French.md
    - "Japanese": Language/Japanese.md
