site_name: 商业笔记
site_url: https://ladygege2494.github.io/notes/business/
theme:
  name: material
  language: zh
  favicon: ../../favicon.jpg
  custom_dir: overrides
  palette:
    primary: red
    accent: red
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
extra:
  homepage: /business/
nav:
  - Home: index.md
  - Macro:
    - 概览: Macro/index.md
    - 经济学原理Principles of ecnomics: Macro/经济学原理Principles of ecnomics.md
  - Business Model:
    - 概览: Business Model/index.md
  - Investment: 
    - 概览: Investment/index.md
    - 股票: Investment/股票.md
  - Leverage:
    - 概览: Leverage/index.md
  - Soft Skills:
    - 概览: Soft Skills/index.md
