site_name: 一路走来
site_url: https://ladygege2494.github.io/notes/journey/
site_description: 记录个人生活与成长感悟
site_author: LadyGege

theme:
  name: material
  language: zh
  favicon: /favicon.jpg
  icon:
    logo: material/map-marker-path
  custom_dir: ../overrides
  font: false
  palette:
    - scheme: default
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips

extra:
  homepage: /journey/

extra_css:
  - /assets/mkdocs-extra.css

extra_javascript:
  - /assets/mkdocs.js

nav:
  - Home: index.md
  - Health: Health/index.md
  - Moments: Moments/index.md
  - Thoughts:
    - 概览: Thoughts/index.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      lang: zh
      separator: '[\s\-，。；：！？、（）【】《》]+'
