site_name: 一路走来
site_description: 记录个人生活与成长感悟
site_author: LadyGege

theme:
  name: material
  language: zh
  favicon: ../../favicon.jpg
  custom_dir: overrides
  palette:
    primary: green
    accent: light green
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight

extra:
  homepage: ../../journey/index.html

nav:
  - Home: index.md
  - Health: Health/index.md
  - Moments: Moments/index.md
  - Thoughts:
    - 概览: Thoughts/index.md
    - 我想如何度过我的本科: Thoughts/我想如何度过我的本科.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed

plugins:
  - search
